### ISSUE TITLE
华为机型无效

### ISSUE THREAD

**Issue by MarkMjw** [liangjingkanji/soft-input-event#1]
试了下Demo，在华为Mate 30 Pro（鸿蒙2.0 & Android 10）上无效，vivo x60（Android 11）可用。

https://user-images.githubusercontent.com/4126838/167077728-312d7d7e-db1a-4aa2-b70c-d04fd0ee7e55.mp4

**Comment by liangjingkanji** [comment]
MIUI和鸿蒙的确存在问题, 等我适配下, 但是这两个系统平滑动画可能无法实现

**Comment by liangjingkanji** [comment]
请尝试最新版本是否已修复

**Comment by liangjingkanji** [comment]
你这个录屏为什么背景都是黑色的

**Comment by MarkMjw** [comment]
> 请尝试最新版本是否已修复

已修复，完美~

**Comment by liangjingkanji** [comment]
并不太完美, 部分机型的平滑动画无效了, 目前只能期待下鸿蒙/小米/谷歌来适配下了

但是我看全网目前只有这个方案是最流畅和耦合度最低的
