### ISSUE TITLE
BottomSheetDialogFragment和Fragment调用setWindowSoftInput，isSupportInsetsFiled不一样

### ISSUE THREAD

**Issue by keternity** [liangjingkanji/soft-input-event#2]
https://user-images.githubusercontent.com/16664891/174560940-8b1fd3a2-b119-4d80-88b6-59957f1b5104.mp4

应用启动，在BottomSheetDialogFragment中调用setWindowSoftInput，发现isSupportInsetsFiled为true。应用杀掉，再启动，如果在Fragment或Activity中调用setWindowSoftInput，发现isSupportInsetsFiled为false。

麻烦大佬看一下，膜拜！！！

**Comment by keternity** [comment]
华为P20，android 9

**Comment by liangjingkanji** [comment]
华为的确存在兼容问题, 恭喜你发现问题所在

**Comment by keternity** [comment]
那麻烦大佬了[膜拜]

**Comment by liangjingkanji** [comment]
我也不咋会, 得研究下

**Comment by liangjingkanji** [comment]
使用最新版本
```kotlin
implementation 'com.github.liangjingkanji:soft-input-event:1.0.7'
```
