### ISSUE TITLE
键盘弹出的时候切换到后台，再切换回来键盘消失了，被顶起的View没下去

### ISSUE THREAD

**Issue by xiaolong125** [liangjingkanji/soft-input-event#4]
## 截图
![20220812-145033](https://user-images.githubusercontent.com/19902247/184300158-d395fea1-94e2-4169-991c-57a4e86cd83b.jpeg)

## 版本
- soft-input-event:1.0.7

**Comment by liangjingkanji** [comment]
在我的设备无法复现, 我的设备在回到后台时会自动隐藏键盘

我建议你提供设备信号和Android版本, 并且最好能提供视频

**Comment by xiaolong125** [comment]
https://user-images.githubusercontent.com/19902247/189797408-12b70fb8-e730-483c-b8a0-5c132c41989f.mp4

手机是Redmi Note 10，系统版本是Android11，还有一个RedMi K50，Android12也是这样

**Comment by liangjingkanji** [comment]
我缺乏设备复现问题, 你可以尝试配置`android:windowSoftInputMode`来修复问题, 欢迎发起pr

**Comment by liangjingkanji** [comment]
已修复, 现在`onPause`就会自动隐藏键盘
