### ISSUE TITLE
软键盘上加一条工具栏，但是布局不滚动

### ISSUE THREAD

**Issue by AversonCoder** [liangjingkanji/soft-input-event#5]
如题，能实现比如输入框软键盘弹出后，在软键盘上方仅做一个小型布局提示输入注意事项。但是整体布局只是覆盖不滚动。谢谢

**Comment by liangjingkanji** [comment]
能否fork仓库复现问题

**Comment by AversonCoder** [comment]
![image](https://user-images.githubusercontent.com/13031684/196575753-e3005e2f-8ab8-4cc2-8aa6-4988d9bd3d80.png)

类似这样一个场景。能在键盘上面显示一条提示栏。但是布局不顶置或导致滚动。

**Comment by liangjingkanji** [comment]
你方法调用参数应该有错误吧, 我不确定你传入的是哪个布局, 请fork仓库复现问题
